### ISSUE TITLE
tones of questions why steal and steal-tools are not working

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#578]
i tried my best to explain the problems i have with steal and steal-tools
http://forums.donejs.com/t/many-problems-with-multipage-app-build/150

i know your focus is not to much on building multi page apps.
but i think there is a community out there that havent a node server for the backend.

**Comment by matthewp** [comment]
@pYr0x Are all of your issues fixed now, can we close this?

**Comment by pYr0x** [comment]
check this out today and give you a feedback

**Comment by pYr0x** [comment]
i could solved many problems
http://forums.donejs.com/t/many-problems-with-multipage-app-build/150/2?u=pyr0x

steal-sass is still not working as expected!
